# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: reconst_freewater
description: Run freewater modelling pipeline using AMICO from DWI data.
keywords:
  - Diffusion MRI
  - Freewater
  - Microstructure modeling
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
  - Freewater:
      description: Free water elimination and mapping from diffusion MRI.
      doi: 10.1002/mrm.22055
      identifier: ""
  - AMICO:
      description: Accelerated Microstructure Imaging via Convex Optimization.
      homepage: https://github.com/daducci/AMICO
      doi: 10.1016/j.neuroimage.2014.10.026
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI file acquired with a freewater compatible protocol (single-shell
          or multi-shell).
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
    - mask:
        type: file
        description: Nifti brain mask.
        pattern: "*mask.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - kernels:
        type: directory
        description: Folder containg kernels.
        pattern: kernels
    - para_diff:
        type: float
        description: Parallel diffusivity value (diff prior).
        optional: true
    - iso_diff:
        type: float
        description: Isotropic diffusivity value (diff prior).
        optional: true
    - perp_diff_min:
        type: float
        description: Minimum perpendicular diffusivity value (diff prior).
        optional: true
    - perp_diff_max:
        type: float
        description: Maximum perpendicular diffusivity value (diff prior).
        optional: true
output:
  dwi_fw_corrected:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__dwi_fw_corrected.nii.gz":
          type: file
          description: Nifti file freewater corrected DWI.
          pattern: "*__dwi_fw_corrected.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  dir:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__dir.nii.gz":
          type: file
          description: Nifti file main direction.
          pattern: "*__dir.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  fibervolume:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__FiberVolume.nii.gz":
          type: file
          description: Nifti file for fiber volume.
          pattern: "*__FiberVolume.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  fw:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__FW.nii.gz":
          type: file
          description: Nifti file for freewater (isotropic volume).
          pattern: "*__FIT_FW.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  nrmse:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__NRMSE.nii.gz":
          type: file
          description: Nifti file for nrmse.
          pattern: "*__NRMSE.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  kernels:
    - kernels:
        type: directory
        description: Folder containing kernels.
        pattern: kernels
  versions:
    - versions.yml:
        type: file
        description: File containing software versions.
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@karanphil"
