---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "bundle_recognize"
description: Extract bundles from one (or more) tractograms
keywords:
  - Diffusion MRI
  - Tractogram
  - Segmentation
  - Bundles
tools:
  - "Scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - tractograms:
      type: file
      description: Tractogram file(s) for bundle extraction [Mandatory]
      pattern: "*.trk"

  - transform:
      type: file
      description: Transform matrix bringing the atlas to native space [Mandatory]
      pattern: "*.mat"

  - config:
      type: file
      description: Bundle atlas configuration file [Mandatory]
      pattern: "*.json"

  - directory:
      type: directory
      description: Directory containing the reference atlas [Mandatory]

args:
  - minimal_vote_ratio:
      type: float
      description: "Streamlines will only be considered for saving if recognized often enough. 
                    The ratio is a value between 0 and 1."
      default: 0.5
  - seed:
      type: int
      description: "Random number generator seed."
      default: 0
  - rbx_processes:
      type: int
      description: "Number of process used."
      default: 0
  - outlier_alpha:
      type: float
      description: "Percent of the length of the tree that clusters of individual streamlines will be pruned."
      default: 0.6
  - run_qc:
      type: boolean
      description: "Generate MultiQC outputs."
      default: "false"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bundles:
      type: file
      description: Segmented and cleaned bundles
      pattern: "*.trk"

  - mqc:
      type: file
      description: PNG file containing quality control image for all bundles. Made for use in MultiQC report.
      pattern: "*_bundles_mosaic_mqc.png"

  - global_mqc:
      type: file
      description: JSON file containing basic measurements of all bundles. Made for use in MultiQC report.
      pattern: "*_bundles_stats_mqc.json"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@CHrlS98"
