name: "pydeface"
description: Remove facial structures from MRI NIfTI images using PyDeface.
keywords:
  - neuroimaging
  - MRI
  - NIfTI
  - anonymization
  - defacing
authors:
  - "@loboehme1"
maintainers:
  - "@loboehme1"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information.
          Expected keys for this module currently include `subject` and `session`,
          for example `[ subject: '01', session: '001' ]`.
    - nifti:
        type: file
        description: |
          Input anatomical MRI image in NIfTI format.
        pattern: "*.{nii,nii.gz}"
output:
  defaced:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information.
            Expected keys for this module currently include `subject` and `session`,
            for example `[ subject: '01', session: '001' ]`.
      - sub-${meta.subject}/ses-${meta.session}/anat/*_defaced.nii.gz: {}
  versions_pydeface:
    - - "${task.process}":
          type: string
          description: The name of the process.
      - "pydeface":
          type: string
          description: The name of the tool.
      - "pydeface_version":
          type: string
          description: The version of PyDeface used by the process.
tools:
  - "pydeface":
      description: "A tool to remove facial structure from MRI images."
      homepage: "https://www.poldracklab.org"
      documentation: "https://github.com/poldracklab/pydeface"
      tool_dev_url: "https://github.com/poldracklab/pydeface"
      doi: "10.5281/zenodo.6856482"
      licence:
        - "MIT"
      identifier: ""
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process.
      - "pydeface":
          type: string
          description: The name of the tool.
  '"versions"':
    - versions.yml:
        type: string
        description: The name of the process.
