# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: registration_anattodwi
description: |
  Registration computing transformations moving images from anatomical space into diffusion space. The `moving_anat` image
  represents the anatomical space, moving to diffusion space, onto its `fixed_reference` and its `metric` representations.

  Configuration, direction and order of the registration follows the [tractoflow](https://doi.org/10.1016/j.neuroimage.2020.116889)
  publication.
keywords:
  - nifti
  - registration
  - anatomical
  - dwi
tools:
  - ANTs:
      description: "Advanced Normalization Tools."
      homepage: "https://github.com/ANTsX/ANTs"
      documentation: "http://stnava.github.io/ANTsDoc/"
      doi: "10.1038/s41598-021-87564-6"
  - ImageMagick:
      description: "ImageMagick is a software suite to create, edit, compose, or convert bitmap images."
      homepage: "https://imagemagick.org/"
      documentation: "https://imagemagick.org/script/command-line-processing.php"
  - MRtrix3:
      description: "MRtrix3 is a software package for processing diffusion MRI data."
      homepage: "https://www.mrtrix3.org/"
      documentation: "https://mrtrix.readthedocs.io/en/latest/"
      doi: "10.1016/j.neuroimage.2019.116137"
  - Scilpy:
      description: "Scilpy is a Python library for processing diffusion MRI data."
      homepage: "https://github.com/scilus/scilpy"
      documentation: "https://scilpy.readthedocs.io/en/latest/"
args:
  - run_qc:
      type: boolean
      description: "Run quality control for the registration process"
      default: false
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fixed_reference:
        type: file
        description: Nifti image file - fixed DWI reference (usually b0)
        pattern: "*.{nii,nii.gz}"
        mandatory: true
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - moving_anat:
        type: file
        description: Nifti image file - moving anat to register (usually T1w)
        pattern: "*.{nii,nii.gz}"
        mandatory: true
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - metric:
        type: file
        description: Nifti image file - additional fixed metric (usually FA)
        pattern: "*.{nii,nii.gz}"
        mandatory: true
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  anat_warped:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_warped.nii.gz":
          type: file
          description: Anatomical image warped to DWI space
          pattern: "*_warped.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  forward_affine:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__forward1_affine.mat":
          type: file
          description: Affine transformation matrix to fixed space.
          pattern: "*__forward1_affine.mat"
          ontologies: []
  forward_warp:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__forward0_warp.nii.gz":
          type: file
          description: Deformation field to fixed space.
          pattern: "*__forward0_warp.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  backward_warp:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__backward1_warp.nii.gz":
          type: file
          description: Deformation field to moving space.
          pattern: "*__backward1_warp.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  backward_affine:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__backward0_affine.mat":
          type: file
          description: Affine transformation matrix to moving space.
          pattern: "*__backward0_affine.mat"
          ontologies: []
  forward_image_transform:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__forward*.{nii.gz,mat}":
          type: list
          description: |
            Tuple, Transformation files to warp images in fixed space, in the correct order
            for REGISTRATION_TRANSFORMTRACTOGRAM : [ meta, [ forward_warp, forward_affine ] ].
          pattern: "*__forward*.{nii.gz,mat}"
          ontologies: []
  backward_image_transform:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__backward*.{nii.gz,mat}":
          type: list
          description: |
            Tuple, transformation files to warp images in moving space, in the correct order
            for REGISTRATION_TRANSFORMTRACTOGRAM : [ meta, [ backward_affine, backward_warp ] ].
          pattern: "*__backward*.{nii.gz,mat}"
          ontologies: []
  forward_tractogram_transform:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__backward*.{nii.gz,mat}":
          type: list
          description: |
            Tuple, transformation files to warp tractograms into fixed space, in the correct order
            for REGISTRATION_TRANSFORMTRACTOGRAM : [ meta, [ backward_affine, backward_warp ] ].
          pattern: "*__backward*.{nii.gz,mat}"
          ontologies: []
  backward_tractogram_transform:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__forward*.{nii.gz,mat}":
          type: list
          description: |
            Tuple, transformation files to warp tractograms into moving space, in the correct order
            for REGISTRATION_TRANSFORMTRACTOGRAM : [ meta, [ forward_affine, forward_warp ] ].
          pattern: "*__forward*.{nii.gz,mat}"
          ontologies: []
  mqc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_registration_anattodwi_mqc.gif":
          type: file
          description: |
            .gif file containing quality control image for the
            registration process. For use in MultiQC report.
          pattern: "*_registration_anattodwi_mqc.gif"
          optional: true
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@medde"
  - "@AlexVCaron"
