# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: tracking_pfttracking
description: Compute include and exclude maps, and the seeding mask from partial volume
  estimation (PVE) maps. Generates a tractogram using anatomically-constrained particle
  filter tracking, Particle Filtering Tractography (PFT).
keywords:
  - Diffusion MRI
  - Tractography
  - Particle Filtering Tractography
tools:
  - DIPY:
      description: DIPY is the paragon 3D/4D+ imaging library in Python.
      homepage: https://dipy.org
      doi: "10.1016/j.neuroimage.2014.04.074"
      identifier: ""
  - scilpy:
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
      identifier: ""
args:
  - pft_fa_seeding_mask_threshold:
      type: float
      default: 0.1
      description: "FA threshold for the seeding mask."
  - pft_wm_seeding_mask_threshold:
      type: float
      default: 0.5
      description: "WM threshold for the seeding mask."
  - pft_seeding_mask_type:
      type: string
      default: "wm"
      choices:
        - "wm"
        - "fa"
      description: Strategy to use to compute the seeding mask.
  - pft_step:
      type: float
      default: 0.2
      description: Tracking Step size.
  - pft_random_seed:
      type: int
      default: 0
      description: Seed for random number generators.
  - pft_seeding:
      type: string
      default: "npv"
      choices:
        - "npv"
        - "nt"
      description: Seeding strategy, either Number Per Voxel (npv) or Number Total (nt).
  - pft_nbr_seeds:
      type: int
      default: 5
      description: Number of seeds per voxel (if npv) or total number of seeds (if nt).
  - pft_min_len:
      type: float
      default: 10.0
      description: Minimum length of streamlines to keep.
  - pft_max_len:
      type: float
      default: 300.0
      description: Maximum length of streamlines to keep.
  - pft_theta:
      type: float
      default: 40.0
      description: Maximum angular difference between tracking steps, in degrees.
  - pft_sfthres:
      type: float
      default: 0.1
      description: Spherical function threshold for tracking.
  - pft_sfthres_init:
      type: float
      default: 0.5
      description: Initial spherical function threshold for tracking.
  - pft_algo:
      type: string
      default: "prob"
      choices:
        - "det"
        - "prob"
      description: Algorithm to use for tracking.
  - pft_compress_value:
      type: float
      default: 0.0
      description: Compression value for the streamlines, in mm. If 0, no compression
        is applied.
  - basis:
      type: string
      default: "descoteaux07_legacy"
      choices:
        - "descoteaux07_legacy"
        - "descoteaux07"
        - "tournier07"
        - "tournier07_legacy"
      description: Spherical basis used for FODF reconstruction.
  - pft_particles:
      type: int
      default: 15
      description: Number of particles to use in the particle filter tracking.
  - pft_back:
      type: float
      default: 2.0
      description: Backtracking distance in mm.
  - pft_front:
      type: float
      default: 1.0
      description: Front tracking distance in mm.
  - run_qc:
      type: boolean
      default: true
      description: Whether to run quality control (QC) on the tracking results.
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - wm:
        type: file
        description: Nifti white matter probability map.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - gm:
        type: file
        description: Nifti grey matter probability map.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - csf:
        type: file
        description: Nifti cerebrospinal fuild probability map.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - fodf:
        type: file
        description: Nifti image of Spherical harmonic file (fodf).
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - fa:
        type: file
        description: Nifti image of FA.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  trk:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking.trk":
          type: file
          description: Tractogram output file.
          pattern: "*__pft_tracking.{trk,tck}"
          ontologies: []
  config:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_config.json":
          type: file
          description: Json file containing tracking parameters.
          pattern: "*__pft_tracking_config.{json}"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  includes:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__map_include.nii.gz":
          type: file
          description: |
            Nifti probability map for tracking of ending the
            streamline and including it in the output.
          pattern: "*__map_include.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  excludes:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__map_exclude.nii.gz":
          type: file
          description: |
            Nifti probability map for tracking of ending the
            streamline and excluding it in the output.
          pattern: "*__map_exclude.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  seeding:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_seeding_mask.nii.gz":
          type: file
          description: Nifti seeding mask for tracking.
          pattern: "*__pft_seeding_mask.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  mqc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_mqc.png":
          type: file
          description: |
            PNG file containing quality control image for tracking.
            Made for use in MultiQC report.
          pattern: "*__pft_tracking_mqc.png"
          ontologies: []
  global_mqc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_stats.json":
          type: file
          description: |
            JSON file containing basic measurements of whole tractogram.
            Made for use in MultiQC report.
          pattern: "*__pft_tracking_stats.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@Manonedde"
