# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: tracking_pfttracking
description: Compute include and exclude maps, and the seeding mask from partial volume
  estimation (PVE) maps. Generates a tractogram using anatomically-constrained particle
  filter tracking, Particle Filtering Tractography (PFT).
keywords:
  - Diffusion MRI
  - Tractography
  - Particle Filtering Tractography

tools:
  - DIPY:
      description: DIPY is the paragon 3D/4D+ imaging library in Python.
      homepage: https://dipy.org
      doi: 10.1016/j.neuroimage.2014.04.074

  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox.
      homepage: https://github.com/scilus/scilpy.git

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - wm:
        type: file
        description: Nifti white matter probability map.
        pattern: "*.{nii,nii.gz}"

    - gm:
        type: file
        description: Nifti grey matter probability map.
        pattern: "*.{nii,nii.gz}"

    - csf:
        type: file
        description: Nifti cerebrospinal fuild probability map.
        pattern: "*.{nii,nii.gz}"

    - fodf:
        type: file
        description: Nifti image of Spherical harmonic file (fodf).
        pattern: "*.{nii,nii.gz}"

    - fa:
        type: file
        description: Nifti image of FA.
        pattern: "*.{nii,nii.gz}"

output:
  - trk:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking.trk":
          type: file
          description: Tractogram output file.
          pattern: "*__pft_tracking.{trk,tck}"
  - config:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_config.json":
          type: file
          description: Json file containing tracking parameters.
          pattern: "*__pft_tracking_config.{json}"
  - includes:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__map_include.nii.gz":
          type: file
          description: |
            Nifti probability map for tracking of ending the
            streamline and including it in the output.
          pattern: "*__map_include.{nii,nii.gz}"
  - excludes:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__map_exclude.nii.gz":
          type: file
          description: |
            Nifti probability map for tracking of ending the
            streamline and excluding it in the output.
          pattern: "*__map_exclude.{nii,nii.gz}"
  - seeding:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_seeding_mask.nii.gz":
          type: file
          description: Nifti seeding mask for tracking.
          pattern: "*__pft_seeding_mask.{nii,nii.gz}"
  - mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_mqc.png":
          type: file
          description: |
            PNG file containing quality control image for tracking.
            Made for use in MultiQC report.
          pattern: "*__pft_tracking_mqc.png"
  - global_mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__pft_tracking_stats.json":
          type: file
          description: |
            	JSON file containing basic measurements of whole tractogram.
              Made for use in MultiQC report.
          pattern: "*__pft_tracking_stats.json"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@Manonedde"
