# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: segmentation_fastseg
description: Perform Brain Tissues Segmentation using FSL fast on a T1 image. Optionally,
  a binary mask of lesion can be add to correct the white matter mask.
keywords:
  - Segmentation
  - T1
  - Tissues
tools:
  - FSL:
      description: FSL Toolbox
      homepage: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
      doi: 10.1016/j.neuroimage.2011.09.015
      identifier: ""
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - image:
        type: file
        description: Nifti T1 volume to segment into tissue maps.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - lesion:
        type: file
        description: Nifti lesion volume to correct the white matter with a lesion mask.
          The lesion mask must be a binary mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  wm_mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*mask_wm.nii.gz":
          type: file
          description: Nifti WM mask volume.
          pattern: "*mask_wm.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  gm_mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*mask_gm.nii.gz":
          type: file
          description: Nifti GM mask volume.
          pattern: "*mask_gm.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  csf_mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*mask_csf.nii.gz":
          type: file
          description: Nifti CSF mask volume.
          pattern: "*mask_csf.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  wm_map:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*map_wm.nii.gz":
          type: file
          description: Nifti WM map volume.
          pattern: "*map_wm.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  gm_map:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*map_gm.nii.gz":
          type: file
          description: Nifti GM map volume.
          pattern: "*map_gm.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  csf_map:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*map_csf.nii.gz":
          type: file
          description: Nifti CSF map volume.
          pattern: "*map_csf.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@gagnonanthony"
