# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-neuro/modules/main/modules/meta-schema.json
name: reconst_fodf
description: Perform FODF reconstruction and compute FODF metrics from a dwi volume
  for a selected number of shells. Note that multiple choices of FODF reconstruction
  method are available through the method argument. The single-shell single-tissue
  (ssst) method is performed by selecting only one shell (task.ext.fodf_shells) and
  choosing the ssst method (task.ext.method). The multi-shell single-tissue (msst)
  method (default) is performed by selecting multiple shells (task.ext.fodf_shells)
  and choosing the ssst method (task.ext.method). Both ssst and msst are expected
  to output only WM FODF. The multi-shell multi-tissue (msmt) method is performed
  by selecting multiple shells (task.ext.fodf_shells) and choosing the msmt method
  (task.ext.method). The msmt method is expected to output WM FODF, GM FODF and CSF
  FODF, along with volume fraction (vf) maps. In every case, chosen FODF metrics are
  outputed.
keywords:
  - FODF
  - Local Model
  - Reconst
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
args:
  - dwi_shell_tolerance:
      type: integer
      description: |
        Tolerance in s/mm2 for grouping b-values into shells.
        E.g. with a tolerance of 20, b-values between 0 and 20 will be considered
        as b=0.
      default: None
  - min_fodf_shell_value:
      type: integer
      description: |
        Minimum b-value to use for FODF fitting. All shells above this value will
        be used.
      default: 100
  - b0_thr_extract_b0:
      type: integer
      description: Threshold under which b-values are considered to be b0s.
      default: 10
  - fodf_shells:
      type: string
      description: |
        Space separated list of b-values to use for FODF fitting. If None, all shells
        above min_fodf_shell_value will be used.
      default: None
  - sh_order:
      type: integer
      description: Spherical harmonics order to use for FODF fitting.
      default: None
  - sh_basis:
      type: string
      description: Spherical harmonics basis to use for FODF fitting.
      default: None
      choices: "tournier07, descoteaux07, descoteaux07_legacy, tournier07_legacy"
  - method:
      type: string
      description: FODF reconstruction method to use.
      default: "ssst"
      choices: "ssst, msmt"
  - relative_threshold:
      type: float
      description: Relative threshold to apply on FODF peaks.
      default: None
  - fodf_metrics_a_factor:
      type: float
      description: Absolute threshold to apply on FODF peaks.
      default: 2.0
  - fa_threshold:
      type: float
      description: Threshold to apply on the FA map to extract voxels in ventricles.
      default: None
  - md_threshold:
      type: float
      description: Threshold to apply on the MD map to extract voxels in ventricles.
      default: None
  - absolute_peaks:
      type: boolean
      description: |
        If set, the peak values are not max-normalized for each voxel, but
        kept as the actual fODF amplitude.
      default: false
  - wm_fodf:
      type: boolean
      description: If set, will output the white matter (WM) FODF map when using
        the msmt method.
      default: true
  - gm_fodf:
      type: boolean
      description: If set, will output the grey matter (GM) FODF map when using
        the msmt method.
      default: false
  - csf_fodf:
      type: boolean
      description: If set, will output the CSF FODF map when using the msmt method.
      default: false
  - vf:
      type: boolean
      description: If set, will output the volume fraction (vf) maps when using the
        msmt method.
      default: false
  - vf_rgb:
      type: boolean
      description: If set, will output the volume fraction (vf) maps in rgb when using
        the msmt method.
      default: false
  - peaks:
      type: boolean
      description: If set, will output the peaks file.
      default: false
  - peak_values:
      type: boolean
      description: If set, will output the peak values file.
      default: false
  - peak_indices:
      type: boolean
      description: If set, will output the peak indices file.
      default: false
  - afd_max:
      type: boolean
      description: If set, will output the maximum Apparent Fiber Density (AFDmax)
        map.
      default: false
  - afd_total:
      type: boolean
      description: If set, will output the total Apparent Fiber Density (AFDtotal)
        map.
      default: false
  - afd_sum:
      type: boolean
      description: If set, will output the sum of all Apparent Fiber Density (Afdsum)
        map.
      default: false
  - nufo:
      type: boolean
      description: If set, will output the Number of Fiber Orientation (NuFO) map.
      default: false
  - ventricles_mask:
      type: boolean
      description: If set, will output the ventricle mask estimated from an MD and
        FA threshold.
      default: false
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI volume to reconstruct FODF from.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
    - mask:
        type: file
        description: B0 mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - fa:
        type: file
        description: FA map.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - md:
        type: file
        description: MD map.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - wm_frf:
        type: file
        description: Fiber Response Function (FRF) for the white matter (WM). In the
          case of single-shell method, this should be the only input FRF. In the case
          of multi-shell method, gm_frf and csf_frf are also mandatory.
        pattern: "*.txt"
        ontologies: []
    - gm_frf:
        type: file
        description: Fiber Response Function (FRF) for the grey matter (GM). Only use
          with multi-shell method, along with wm_frf and csf_frf.
        pattern: "*.txt"
        ontologies: []
    - csf_frf:
        type: file
        description: Fiber Response Function (FRF) for the CSF. Only use with multi-shell
          method, along with wm_frf and gm_frf.
        pattern: "*.txt"
        ontologies: []
output:
  fodf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fodf.nii.gz":
          type: file
          description: FODF map.
          pattern: "*__fodf.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  wm_fodf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__wm_fodf.nii.gz":
          type: file
          description: WM FODF map.
          pattern: "*__wm_fodf.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  gm_fodf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__gm_fodf.nii.gz":
          type: file
          description: GM FODF map.
          pattern: "*__gm_fodf.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  csf_fodf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__csf_fodf.nii.gz":
          type: file
          description: CSF FODF map.
          pattern: "*__csf_fodf.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  vf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__vf.nii.gz":
          type: file
          description: Volume fraction map.
          pattern: "*__vf.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  vf_rgb:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__vf_rgb.nii.gz":
          type: file
          description: Volume fraction map in rgb.
          pattern: "*__vf_rgb.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  peaks:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__peaks.nii.gz":
          type: file
          description: Peaks file.
          pattern: "*__peaks.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  peak_values:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__peak_values.nii.gz":
          type: file
          description: Peak values file.
          pattern: "*__peak_values.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  peak_indices:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__peak_indices.nii.gz":
          type: file
          description: Peak indices file.
          pattern: "*__peak_indices.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  afd_max:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__afd_max.nii.gz":
          type: file
          description: Maximum Apparent Fiber Density (AFDmax) map.
          pattern: "*__afd_max.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  afd_total:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__afd_total.nii.gz":
          type: file
          description: Total Apparent Fiber Density (AFDtotal) map.
          pattern: "*__afd_total.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  afd_sum:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__afd_sum.nii.gz":
          type: file
          description: Sum of all Apparent Fiber Density (Afdsum) map.
          pattern: "*__afd_sum.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  nufo:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__nufo.nii.gz":
          type: file
          description: Number of Fiber Orientation (NuFO) map.
          pattern: "*__nufo.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  vent_mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__ventricles_mask.nii.gz":
          type: file
          description: Ventricule mask estimated from an MD and FA threshold.
          pattern: "*__ventricles_mask.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@gagnonanthony"
  - "@karanphil"
