# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: tracking_localtracking
description: process local tracking
keywords:
  - Tractography
  - Local tracking
  - Diffusion MRI
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`

    - wm:
        type: file
        description: Nifti image white matter mask.
        pattern: "*.{nii,nii.gz}"

    - fodf:
        type: file
        description: Nifti image of spherical harmonic file (fodf)
        pattern: "*.{nii,nii.gz}"

    - fa:
        type: file
        description: NIfti image binary mask for fa mask
        pattern: "*.{nii,nii.gz}"

output:
  - trk:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_tracking.trk":
          type: file
          description: Tractogram output file.
          pattern: "*__local_tracking.{trk,tck}"
  - config:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_tracking_config.json":
          type: file
          description: Json file containing tracking parameters.
          pattern: "*__local_tracking_config.{json}"
  - seedmask:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_seeding_mask.nii.gz":
          type: file
          description: Nifti seeding mask for tracking.
          pattern: "*__local_seeding_mask.{nii,nii.gz}"
  - trackmask:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_tracking_mask.nii.gz":
          type: file
          description: Nifti tracking mask
          pattern: "*__local_tracking_mask.{nii,nii.gz}"
  - mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_tracking_mqc.png":
          type: file
          description: |
            PNG file containing quality control image for tracking.
            Made for use in MultiQC report.
          pattern: "*__local_tracking_mqc.png"
  - global_mqc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__local_tracking_stats.json":
          type: file
          description: |
            JSON file containing basic measurements of whole tractogram.
            Made for use in MultiQC report.
          pattern: "*__local_tracking_stats.json"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@scilus"
