name: "bundle_seg"
description: |
  Subworkflow to perform BundleSeg [1] to extract major white matter bundle from a tractogram.

  [1] St-Onge, Etienne, Kurt G. Schilling, and Francois Rheault.
      "BundleSeg: A versatile,reliable and reproducible approach to white
      matter bundle segmentation." International Workshop on Computational
      Diffusion MRI. Cham: Springer Nature Switzerland (2023)

  ---------  Steps  --------------------

  1. Anatomical Registration (ANTs)
      Use the FA map from the subject to register the atlas anatomical file and compute the transformations.
  2. Bundle Recognition (scilpy)
      Perform bundle recognition and extraction using BundleSeg.

  ---------  Experimental features -----

  DISCLAIMER !!!
      The following features are experimental and may not work as expected. While we run tests to ensure
      computational stability of the subworkflow, we cannot guarantee the correctness of the results.

  Anatomical Registration (SynthMorph) : params.run_synthmorph = true
      Synthmorph is a machine learning-based registration method developed by the Freesurfer team. It is made
      available in this subworkflow by the REGISTRATION subworkflow, please refer to its documentation for
      more details.
keywords:
  - BundleSeg
  - WM bundles
  - Tractogram
  - Segmentation
components:
  - bundle/recognize
  - registration
  - utils_options
input:
  - ch_fa:
      type: file
      description: |
        The input channel containing the FA map. This map is used to compute the transformation between the atlas'
        space and the subject's space.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - fa:
            type: file
            description: FA map image file.
      pattern: "*.{nii,nii.gz}"
      mandatory: true
  - ch_tractogram:
      type: file
      description: |
        The input channel containing the whole-brain tractogram to be segmented.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - tractogram:
            type: file
            description: Whole-brain tractogram file.
      pattern: "*.trk"
      mandatory: true
  - ch_freesurfer_license:
      type: file
      description: |
        ONLY USED WITH SYNTHMORPH REGISTRATION. The input channel containing the Freesurfer license file.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - license:
            type: file
            description: Freesurfer license file.
      pattern: "*.txt"
      mandatory: false
  - options:
      type: map
      description: Map of options for the bundle_seg subworkflow.
      mandatory: false
      entries:
        method:
          type: string
          choices: [ants, easyreg, synthmorph]
          description: Registration method to use. Options are 'ants', 'easyreg', or 'synthmorph'.
          default: ants
        atlas_directory:
          type: string
          description: Use an alternative atlas to the default BundleSeg one available on Zenodo (https://zenodo.org/records/10103446). The folder MUST follow the same organisation as archive `atlas.zip` hosted on Zenodo.
          default: null

output:
  - bundles:
      type: file
      description: |
        Channel containing all the segmented bundle files.
      structure:
        - meta:
            type: map
            description: Metadata map.
        - bundles:
            type: file
            description: List of segmented bundle files.
      pattern: "*.trk"
  - mqc:
      type: file
      description: |
        Channel containing QC data for MultiQC reports.
      structure:
        - mqc:
            type: file
            description: MultiQC report file.
      pattern: "*mqc.*"
      mandatory: false
  - bundles_mqc:
      type: file
      description: |
        Channel containing the bundle segmentation mosaic images for QC.
      structure:
        - bundles_mosaic:
            type: file
            description: Bundle segmentation mosaic image.
      pattern: "*_bundles_mosaic_mqc.png"
      mandatory: false
  - stats_mqc:
      type: file
      description: |
        Channel containing the bundle segmentation statistics for QC.
      structure:
        - stats:
            type: file
            description: Bundle segmentation statistics JSON file.
      pattern: "*_bundles_stats_mqc.json"
      mandatory: false
  - versions:
      type: file
      description: |
        File containing software versions
      structure:
        - versions:
            type: file
            description: Versions YAML file.
      pattern: "versions.yml"
authors:
  - "@gagnonanthony"
  - "@AlexVCaron"
maintainers:
  - "@gagnonanthony"
