name: Lint nf-neuro component

on:
  workflow_dispatch:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: choice
        options:
          - module
          - subworkflow
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"
  workflow_call:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: string
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"

run-name: Lint ${{ inputs.component }}
jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    name: lint - ${{ inputs.component }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Python
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_delay: 5000
          action: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with: |
            python-version: "3.10"

      - uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # v3.0.0
        with:
          poetry-version: "1.8.*"

      - name: Setup Java
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_delay: 5000
          action: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
          with: |
            distribution: "temurin"
            java-version: "17"

      - name: Setup nextflow
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_delay: 5000
          action: nf-core/setup-nextflow@561fcfc7146dcb12e3871909b635ab092a781f34 # v2.0.0
          with: |
            version: ${{ inputs.nextflow_version }}

      - name: Install nf-core tools
        run: |
          poetry install --no-root

      - name: Lint ${{ inputs.type }} ${{ inputs.component }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: |
          poetry run nf-core --verbose ${{ inputs.type }}s \
            --git-remote https://github.com/${{ github.repository }}.git \
            lint ${{ inputs.component }}

      - name: Convert component meta.yml to markdown
        run: |
          poetry run python docs/astro/convert_${{ inputs.type }}.py \
            ${{ inputs.type }}s/nf-neuro/${{ inputs.component }}/meta.yml \
            ${{ github.sha }} \
            $(echo "${{ inputs.component }}" | sed 's/\//_/g').md
